### ISSUE TITLE
error retrieving array field

### ISSUE THREAD

**Issue by rafsAcorsi** [JavierLuna/datastorm#14]
Hello!
I have a datastore kind that has an array field, when trying to retrieve that kind using datastorm I get the error below:

"""
self = < Settings >, name = 'load_stuffs'
value = ['ball', 'fire', 'file']
field = None

    def set(self, name, value, field=None):
>       field = field or self.__datastorm_fields.get(value, AnyField)
E       TypeError: unhashable type: 'list'
"""

**Comment by JavierLuna** [comment]
On it!

**Comment by JavierLuna** [comment]
#15

**Comment by JavierLuna** [comment]
Fixed on 0.0.0a6
